BOARD = GENERIC_RP_RP2040
CONVERT_TO = kb2040

LTO_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
COMBO_ENABLE = yes
INDICATOR_LIGHTS = yes
CAPS_WORD_ENABLE = yes
# TAP_DANCE_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
SWAP_HANDS_ENABLE = yes
