BOARD = GENERIC_RP_RP2040
CONVERT_TO = kb2040

LAYOUTS = split_3x5_3 split_3x6_3

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
INDICATOR_LIGHTS = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306

DEFAULT_FOLDER = crkbd/rev1
